#!/home/jack/Desktop/Kokoro-TTS-Pause/venv/bin/python
import os
import random
import shutil
from flask import Flask, render_template_string, send_from_directory
from icecream import ic

# ===========================================
# Configuration
# ===========================================
app = Flask(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")
SELECTED_DIR = os.path.join(STATIC_DIR, "selected")

# Create the selected directory if not exists
os.makedirs(SELECTED_DIR, exist_ok=True)

# ===========================================
# Helper Functions
# ===========================================
def is_image_file(filename):
    """Check if file has a valid image extension."""
    extensions = (".jpg", ".jpeg", ".png", ".webp")
    return filename.lower().endswith(extensions)


def clear_selected_folder():
    """Delete all files from the selected folder before each new scan."""
    for f in os.listdir(SELECTED_DIR):
        path = os.path.join(SELECTED_DIR, f)
        if os.path.isfile(path):
            os.remove(path)
    ic("Cleared old selection in static/selected")


def scan_and_copy_images():
    """Scan each subdirectory, copy 4 random images to the selected folder."""
    clear_selected_folder()
    subdir_images = {}

    for root, dirs, files in os.walk(STATIC_DIR):
        if root == SELECTED_DIR:
            continue  # skip our target folder itself

        # Only consider subdirectories under static/
        if root == STATIC_DIR:
            continue

        valid_images = [f for f in files if is_image_file(f)]
        if not valid_images:
            continue

        subdir_name = os.path.basename(root)
        selected = random.sample(valid_images, min(10, len(valid_images)))
        ic(f"Selected {selected} from {subdir_name}")

        copied_files = []
        for img in selected:
            src = os.path.join(root, img)
            new_name = f"{subdir_name}_{img}"
            dst = os.path.join(SELECTED_DIR, new_name)
            shutil.copy2(src, dst)
            copied_files.append(new_name)

        subdir_images[subdir_name] = copied_files

    return subdir_images


# ===========================================
# Routes
# ===========================================
@app.route("/")
def index():
    """Main page to display random images grouped by subdirectory."""
    images_by_folder = scan_and_copy_images()

    html_template = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Random Image Sampler</title>
        <style>
            body { background: #0e0e0e; color: #fff; font-family: Arial; text-align: center; }
            h2 { color: #ffcc00; margin-top: 40px; }
            .folder { margin: 20px auto; border-bottom: 1px solid #444; padding-bottom: 20px; }
            .images { display: flex; justify-content: center; flex-wrap: wrap; gap: 10px; margin-top: 10px; }
            img { width: 180px; height: auto; border-radius: 10px; box-shadow: 0 0 10px #444; transition: 0.3s; }
            img:hover { transform: scale(1.05); box-shadow: 0 0 15px #ffcc00; }
            .footer { margin-top: 50px; color: #888; font-size: 14px; }
            button { background: #ffcc00; border: none; padding: 10px 20px; margin-top: 30px; border-radius: 5px; cursor: pointer; font-size: 16px; }
            button:hover { background: #ffaa00; }
            a{
            color:yellow; font-size:2vw;
            }
        </style>
    </head>
    <body>
        <h1>📸 Random Images from Each Folder</h1>
        <a href="http://192.168.1.105:5000/">GALLERY</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="http://192.168.1.105:5100/">CAPTIONIZER</a>
        {% for folder, files in images_by_folder.items() %}
            <div class="folder">
                <h2>{{ folder }}</h2>
                <div class="images">
                    {% for file in files %}
                        <img src="{{ url_for('static', filename='selected/' + file) }}" alt="{{ file }}">
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        <form action="/" method="get">
            <button type="submit">🔄 Refresh Selection</button>
        </form>
        <div class="footer">Generated by Esperanza 🌙 for Jack</div>
    </body>
    </html>
    """

    return render_template_string(html_template, images_by_folder=images_by_folder)


# ===========================================
# Run
# ===========================================
if __name__ == "__main__":
    ic("Starting Flask server at http://127.0.0.1:5000")
    app.run(debug=True, host='0.0.0.0', port=5000)
